### ISSUE TITLE
dubbo的多版本控制

### ISSUE THREAD

**Issue by dingmingdegit** [apache/dubbo#6673]
![image](https://user-images.githubusercontent.com/30460974/91791712-697eb980-ec46-11ea-8836-086442746578.png)
![image](https://user-images.githubusercontent.com/30460974/91791747-81eed400-ec46-11ea-931c-76ef0df17fb4.png)
![image](https://user-images.githubusercontent.com/30460974/91791768-903cf000-ec46-11ea-8d6a-ba24f862af39.png)
使用注解实现多版本控制,无法成功

**Comment by AlbumenJ** [comment]
would u pls provide your dubbo version and registry type of both consumer and provider sides.

**Comment by dingmingdegit** [comment]
> 
> 
> would u pls provide your dubbo version and registry type of both consumer and provider sides.

dubbo版本2.7.6 使用nacos注册中心

**Comment by AlbumenJ** [comment]
This is a known issue in 2.7.6 version that unable to discover interface with only `version` key or `group` key. It had been fixed in latest version. Also, you can try specify with `group` key.

**Comment by TimYi** [comment]
> This is a known issue in 2.7.6 version that unable to discover interface with only `version` key or `group` key. It had been fixed in latest version. Also, you can try specify with `group` key.

@AlbumenJ Maybe this issue still exists in rmi and hessian protocol. See [this issue](https://github.com/apache/dubbo/issues/6737). Please have a look.
